### ISSUE TITLE
Unable to set higher level logs

### ISSUE THREAD

**Issue by wangzhenxing4** [charlie0129/batt#6]
First of all, I'm using automatic setup utility to install the batt (step 1), then go to "/Library/LaunchDaemons/cc.chlc.batt.plist", modify the file. Then use "sudo batt install" to install the daemon, I would like to ask what the normal procedure should be?

**Comment by charlie0129** [comment]
The auto installation script should setup everything for you. You don’t need to modify the launch daemon. If you want to install it manually, you can refer to the manual installation instructions.

On Sep 8, 2023, at 8:40 PM, 王振兴 ***@***.***> wrote:

﻿

First of all, I'm using automatic setup utility to install the batt (step 1), then go to "/Library/LaunchDaemons/cc.chlc.batt.plist", modify the file. Then use "sudo batt install" to install the daemon, I would like to ask what the normal procedure should be?

**Comment by charlie0129** [comment]
Sorry I failed to notice the title. If you want to set higher level logs, the procedure would be:

1. unload daemon `sudo launchctl unload /Library/LaunchDaemons/cc.chlc.batt.plist`
1. edit `/Library/LaunchDaemons/cc.chlc.batt.plist` to set appropriate log level
2. load daemon `sudo launchctl load /Library/LaunchDaemons/cc.chlc.batt.plist`

**Comment by charlie0129** [comment]
Hi, I added the steps to README. I am going to close this issue. If you need additional help, feel free to reopen.
