### ISSUE TITLE
Unable to charge the iphone

### ISSUE THREAD

**Issue by reesecahn** [charlie0129/batt#8]
My Mac is connected to the display screen, but when the battery level is higher than the limit, my phone cannot charge while connected to the Mac.
Please tell me how to resolve this situation, it is very important to me, and I would greatly appreciate your help.

**Comment by charlie0129** [comment]
batt shouldn't cause this issue. Can you please check is there any external issues?

Just to be sure. I tested your scenario a MacBook Air M1 (Monterey and Sonoma) and iPhone 15 Pro. I can't reproduce this issue.

**Comment by reesecahn** [comment]
After I disabled disable-charging-pre-sleep, this issue disappeared. I speculate that this situation is caused by my Mac disabling charging before going to sleep.

**Comment by charlie0129** [comment]
Your phone can't charge _during sleeping_ or _while awake_?

**Comment by diyfixtool** [comment]
It may be a faulty charger, a problem with the charging cable, a problem with the mobile phone charging port, a problem with the mobile phone battery, or a problem with the system settings.

**Comment by diyfixtool** [comment]
Check the charging cable and USB adapter for signs of damage, such as broken or bent prongs. If the internal battery of the mobile phone is broken, you need to replace the battery. The PHONEFIX official website provides battery repair and replacement services, so you can learn more if you need it.
